services:
  - type: web
    name: fullstack-app
    env: python
    buildCommand: |
      cd frontend
      npm install
      npm run mv-build
      cd ../backend
      pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: REACT_APP_PATH
        value: frontend
