export const YearsList = [
  { label: "2005", value: "2005" },
  { label: "2006", value: "2006" },
  { label: "2008", value: "2008" },
  { label: "2009", value: "2009" },
  { label: "2010", value: "2010" },
  { label: "2011", value: "2011" },
  { label: "2012", value: "2012" },
  { label: "2013", value: "2013" },
  { label: "2014", value: "2014" },
  { label: "2015", value: "2015" },
  { label: "2016", value: "2016" },
  { label: "2017", value: "2017" },
  { label: "2018", value: "2018" },
  { label: "2019", value: "2019" },
  { label: "2020", value: "2020" },
  { label: "2021", value: "2021" },
  { label: "2022", value: "2022" },
  { label: "2023", value: "2023" },
];

export const carBrands = [
  { label: "Audi", value: "audi" },
  { label: "Bajaj", value: "bajaj" },
  { label: "BMW", value: "bmw" },
  { label: "Chevrolet", value: "chevrolet" },
  { label: "Citroen", value: "citroen" },
  { label: "Datsun", value: "datsun" },
  { label: "Fiat", value: "fiat" },
  { label: "Ford", value: "ford" },
  { label: "Force", value: "force" },
  { label: "Honda", value: "honda" },
  { label: "Hyundai", value: "hyundai" },
  { label: "ICML", value: "icml" },
  { label: "Isuzu", value: "isuzu" },
  { label: "Jaguar", value: "jaguar" },
  { label: "Jeep", value: "jeep" },
  { label: "Kia", value: "kia" },
  { label: "Land rover", value: "land rover" },
  { label: "Mahindra", value: "mahindra" },
  { label: "Mercedes-benz", value: "mercedes-benz" },
  { label: "Mini", value: "mini" },
  { label: "MG", value: "mg" },
  { label: "Mitsubishi", value: "mitsubishi" },
  { label: "Nissan", value: "nissan" },
  { label: "Opel", value: "opel" },
  { label: "Porsche", value: "porsche" },
  { label: "Premier", value: "premier" },
  { label: "Renault", value: "renault" },
  { label: "Skoda", value: "skoda" },
  { label: "Tata", value: "tata" },
  { label: "Toyota", value: "toyota" },
  { label: "Volkswagen", value: "volkswagen" },
  { label: "Volvo", value: "volvo" },
];

export type CarModel = {
  label: string;
  value: string;
};

export type CarModelsByBrand = {
  [brand: string]: CarModel[];
};

export const carModels: CarModelsByBrand = {
  maruti: [
    {
      label: "Wagon R",
      value: "maruti wagon r",
    },
    {
      label: "Celerio",
      value: "maruti celerio",
    },
    {
      label: "Ertiga",
      value: "maruti ertiga",
    },
    {
      label: "Alto",
      value: "maruti alto",
    },
    {
      label: "Ertiga Tour",
      value: "maruti ertiga tour",
    },
    {
      label: "Swift Dzire Tour",
      value: "maruti swift dzire tour",
    },
    {
      label: "Eeco",
      value: "maruti eeco",
    },
    {
      label: "Estilo",
      value: "maruti estilo",
    },
    {
      label: "Eeco Cargo",
      value: "maruti eeco cargo",
    },
    {
      label: "Alto K10",
      value: "maruti alto k10",
    },
    {
      label: "Alto 800",
      value: "maruti alto 800",
    },
    {
      label: "Zen Estilo",
      value: "maruti zen estilo",
    },
    {
      label: "Celerio Tour 2018-2021",
      value: "maruti celerio tour 2018-2021",
    },
    {
      label: "Xl6",
      value: "maruti xl6",
    },
    {
      label: "Sx4",
      value: "maruti sx4",
    },
    {
      label: "Swift Dzire",
      value: "maruti swift dzire",
    },
    {
      label: "Omni",
      value: "maruti omni",
    },
    {
      label: "S-Presso",
      value: "maruti s-presso",
    },
    {
      label: "Swift",
      value: "maruti swift",
    },
    {
      label: "800",
      value: "maruti 800",
    },
    {
      label: "Super Carry",
      value: "maruti super carry",
    },
    {
      label: "Ciaz",
      value: "maruti ciaz",
    },
    {
      label: "Baleno",
      value: "maruti baleno",
    },
    {
      label: "Ignis",
      value: "maruti ignis",
    },
    {
      label: "Vitara Brezza",
      value: "maruti vitara brezza",
    },
    {
      label: "Sx4 S Cross",
      value: "maruti sx4 s cross",
    },
    {
      label: "Ritz",
      value: "maruti ritz",
    },
    {
      label: "Ciaz S",
      value: "maruti ciaz s",
    },
    {
      label: "A-Star",
      value: "maruti a-star",
    },
    {
      label: "Celerio X",
      value: "maruti celerio x",
    },
    {
      label: "Wagon R Stingray",
      value: "maruti wagon r stingray",
    },
    {
      label: "Esteem",
      value: "maruti esteem",
    },
    {
      label: "Grand Vitara",
      value: "maruti grand vitara",
    },
    {
      label: "Baleno Rs",
      value: "maruti baleno rs",
    },
    {
      label: "Brezza",
      value: "maruti brezza",
    },
    {
      label: "Zen",
      value: "maruti zen",
    },
    {
      label: "Alto 2021",
      value: "maruti alto 2021",
    },
    {
      label: "Gypsy",
      value: "maruti gypsy",
    },
    {
      label: "Kizashi",
      value: "maruti kizashi",
    },
  ],
  honda: [
    {
      label: "Amaze",
      value: "honda amaze",
    },
    {
      label: "City",
      value: "honda city",
    },
    {
      label: "Mobilio",
      value: "honda mobilio",
    },
    {
      label: "Jazz",
      value: "honda jazz",
    },
    {
      label: "Wr-V",
      value: "honda wr-v",
    },
    {
      label: "Brio",
      value: "honda brio",
    },
    {
      label: "Cr-V",
      value: "honda cr-v",
    },
    {
      label: "Br-V",
      value: "honda br-v",
    },
    {
      label: "Civic",
      value: "honda civic",
    },
    {
      label: "Accord",
      value: "honda accord",
    },
  ],
  hyundai: [
    {
      label: "Grand I10",
      value: "hyundai grand i10",
    },
    {
      label: "Santro",
      value: "hyundai santro",
    },
    {
      label: "Aura",
      value: "hyundai aura",
    },
    {
      label: "Grand I10 Nios",
      value: "hyundai grand i10 nios",
    },
    {
      label: "Accent",
      value: "hyundai accent",
    },
    {
      label: "Santro Xing",
      value: "hyundai santro xing",
    },
    {
      label: "Xcent Prime",
      value: "hyundai xcent prime",
    },
    {
      label: "Xcent",
      value: "hyundai xcent",
    },
    {
      label: "I10",
      value: "hyundai i10",
    },
    {
      label: "Eon",
      value: "hyundai eon",
    },
    {
      label: "Kona",
      value: "hyundai kona",
    },
    {
      label: "Verna",
      value: "hyundai verna",
    },
    {
      label: "Creta",
      value: "hyundai creta",
    },
    {
      label: "I20",
      value: "hyundai i20",
    },
    {
      label: "Venue",
      value: "hyundai venue",
    },
    {
      label: "I20 Active",
      value: "hyundai i20 active",
    },
    {
      label: "Elantra",
      value: "hyundai elantra",
    },
    {
      label: "Elite I20 2018",
      value: "hyundai elite i20 2018",
    },
    {
      label: "Getz",
      value: "hyundai getz",
    },
    {
      label: "Sonata",
      value: "hyundai sonata",
    },
    {
      label: "I20 N Line",
      value: "hyundai i20 n line",
    },
    {
      label: "Santa Fe",
      value: "hyundai santa fe",
    },
    {
      label: "Tucson",
      value: "hyundai tucson",
    },
    {
      label: "Alcazar",
      value: "hyundai alcazar",
    },
  ],
  tata: [
    {
      label: "Tiago",
      value: "tata tiago",
    },
    {
      label: "Nano",
      value: "tata nano",
    },
    {
      label: "Tigor",
      value: "tata tigor",
    },
    {
      label: "Tiago Nrg",
      value: "tata tiago nrg",
    },
    {
      label: "Indigo",
      value: "tata indigo",
    },
    {
      label: "Indica",
      value: "tata indica",
    },
    {
      label: "Tigor Ev",
      value: "tata tigor ev",
    },
    {
      label: "Nexon Ev Prime",
      value: "tata nexon ev prime",
    },
    {
      label: "Nexon Ev Max",
      value: "tata nexon ev max",
    },
    {
      label: "Sumo Victa",
      value: "tata sumo victa",
    },
    {
      label: "Hexa",
      value: "tata hexa",
    },
    {
      label: "Aria",
      value: "tata aria",
    },
    {
      label: "Indigo Marina",
      value: "tata indigo marina",
    },
    {
      label: "Sumo",
      value: "tata sumo",
    },
    {
      label: "Winger",
      value: "tata winger",
    },
    {
      label: "Venture",
      value: "tata venture",
    },
    {
      label: "Xenon Xt",
      value: "tata xenon xt",
    },
    {
      label: "Yodha Pickup",
      value: "tata yodha pickup",
    },
    {
      label: "Nexon",
      value: "tata nexon",
    },
    {
      label: "Altroz",
      value: "tata altroz",
    },
    {
      label: "Harrier",
      value: "tata harrier",
    },
    {
      label: "Indica Ev2",
      value: "tata indica ev2",
    },
    {
      label: "Punch",
      value: "tata punch",
    },
    {
      label: "Zest",
      value: "tata zest",
    },
    {
      label: "Manza",
      value: "tata manza",
    },
    {
      label: "Safari Storme",
      value: "tata safari storme",
    },
    {
      label: "Bolt",
      value: "tata bolt",
    },
    {
      label: "New Safari",
      value: "tata new safari",
    },
    {
      label: "Indica Xeta",
      value: "tata indica xeta",
    },
  ],
  toyota: [
    {
      label: "Corolla Altis",
      value: "toyota corolla altis",
    },
    {
      label: "Camry",
      value: "toyota camry",
    },
    {
      label: "Innova",
      value: "toyota innova",
    },
    {
      label: "Innova Crysta",
      value: "toyota innova crysta",
    },
    {
      label: "Prius",
      value: "toyota prius",
    },
    {
      label: "Glanza",
      value: "toyota glanza",
    },
    {
      label: "Urban Cruiser",
      value: "toyota urban cruiser",
    },
    {
      label: "Etios Liva",
      value: "toyota etios liva",
    },
    {
      label: "Etios",
      value: "toyota etios",
    },
    {
      label: "Etios Cross",
      value: "toyota etios cross",
    },
    {
      label: "Fortuner",
      value: "toyota fortuner",
    },
    {
      label: "Yaris",
      value: "toyota yaris",
    },
    {
      label: "Etios 2014-2016",
      value: "toyota etios 2014-2016",
    },
    {
      label: "Corolla",
      value: "toyota corolla",
    },
    {
      label: "Platinum Etios",
      value: "toyota platinum etios",
    },
    {
      label: "Prado",
      value: "toyota prado",
    },
  ],
  bajaj: [
    {
      label: "Re60",
      value: "bajaj re60",
    },
  ],
  mahindra: [
    {
      label: "Bolero Maxi Truck Plus",
      value: "mahindra bolero maxi truck plus",
    },
    {
      label: "Kuv 100 Nxt",
      value: "mahindra kuv 100 nxt",
    },
    {
      label: "E2O",
      value: "mahindra e2o",
    },
    {
      label: "E2O Plus",
      value: "mahindra e2o plus",
    },
    {
      label: "E Verito",
      value: "mahindra e verito",
    },
    {
      label: "Marazzo",
      value: "mahindra marazzo",
    },
    {
      label: "Xylo",
      value: "mahindra xylo",
    },
    {
      label: "Scorpio",
      value: "mahindra scorpio",
    },
    {
      label: "Bolero",
      value: "mahindra bolero",
    },
    {
      label: "Supro",
      value: "mahindra supro",
    },
    {
      label: "Bolero Pik Up Extra Strong",
      value: "mahindra bolero pik up extra strong",
    },
    {
      label: "Bolero Pik Up Extra Long",
      value: "mahindra bolero pik up extra long",
    },
    {
      label: "Bolero Camper",
      value: "mahindra bolero camper",
    },
    {
      label: "Ssangyong Rexton",
      value: "mahindra ssangyong rexton",
    },
    {
      label: "Renault Logan",
      value: "mahindra renault logan",
    },
    {
      label: "Bolero Power Plus",
      value: "mahindra bolero power plus",
    },
    {
      label: "Thar",
      value: "mahindra thar",
    },
    {
      label: "Xuv500",
      value: "mahindra xuv500",
    },
    {
      label: "Xuv300",
      value: "mahindra xuv300",
    },
    {
      label: "Tuv 300",
      value: "mahindra tuv 300",
    },
    {
      label: "Kuv 100",
      value: "mahindra kuv 100",
    },
    {
      label: "Verito",
      value: "mahindra verito",
    },
    {
      label: "Quanto",
      value: "mahindra quanto",
    },
    {
      label: "Bolero Neo",
      value: "mahindra bolero neo",
    },
    {
      label: "Nuvosport",
      value: "mahindra nuvosport",
    },
    {
      label: "Verito Vibe",
      value: "mahindra verito vibe",
    },
    {
      label: "Xuv700",
      value: "mahindra xuv700",
    },
    {
      label: "Logan",
      value: "mahindra logan",
    },
    {
      label: "Tuv 300 Plus",
      value: "mahindra tuv 300 plus",
    },
  ],
  chevrolet: [
    {
      label: "Aveo",
      value: "chevrolet aveo",
    },
    {
      label: "Spark",
      value: "chevrolet spark",
    },
    {
      label: "Beat",
      value: "chevrolet beat",
    },
    {
      label: "Tavera",
      value: "chevrolet tavera",
    },
    {
      label: "Enjoy",
      value: "chevrolet enjoy",
    },
    {
      label: "Cruze",
      value: "chevrolet cruze",
    },
    {
      label: "Sail Hatchback",
      value: "chevrolet sail hatchback",
    },
    {
      label: "Sail",
      value: "chevrolet sail",
    },
    {
      label: "Aveo U-Va",
      value: "chevrolet aveo u-va",
    },
    {
      label: "Captiva",
      value: "chevrolet captiva",
    },
    {
      label: "Optra",
      value: "chevrolet optra",
    },
    {
      label: "Trailblazer",
      value: "chevrolet trailblazer",
    },
  ],
  renault: [
    {
      label: "Triber",
      value: "renault triber",
    },
    {
      label: "Lodgy",
      value: "renault lodgy",
    },
    {
      label: "Duster",
      value: "renault duster",
    },
    {
      label: "Pulse",
      value: "renault pulse",
    },
    {
      label: "Kiger",
      value: "renault kiger",
    },
    {
      label: "Kwid",
      value: "renault kwid",
    },
    {
      label: "Captur",
      value: "renault captur",
    },
    {
      label: "Scala",
      value: "renault scala",
    },
    {
      label: "Fluence",
      value: "renault fluence",
    },
    {
      label: "Koleos",
      value: "renault koleos",
    },
  ],
  nissan: [
    {
      label: "Evalia",
      value: "nissan evalia",
    },
    {
      label: "Micra",
      value: "nissan micra",
    },
    {
      label: "Magnite",
      value: "nissan magnite",
    },
    {
      label: "Terrano",
      value: "nissan terrano",
    },
    {
      label: "Sunny",
      value: "nissan sunny",
    },
    {
      label: "Micra Active",
      value: "nissan micra active",
    },
    {
      label: "Teana",
      value: "nissan teana",
    },
    {
      label: "Kicks",
      value: "nissan kicks",
    },
    {
      label: "X-Trail",
      value: "nissan x-trail",
    },
  ],
  datsun: [
    {
      label: "Go Plus",
      value: "datsun go plus",
    },
    {
      label: "Go",
      value: "datsun go",
    },
    {
      label: "Redigo",
      value: "datsun redigo",
    },
  ],
  kia: [
    {
      label: "Carens",
      value: "kia carens",
    },
    {
      label: "Seltos",
      value: "kia seltos",
    },
    {
      label: "Sonet",
      value: "kia sonet",
    },
  ],
  force: [
    {
      label: "Trax Cruiser",
      value: "force trax cruiser",
    },
    {
      label: "One",
      value: "force one",
    },
    {
      label: "Gurkha",
      value: "force gurkha",
    },
  ],
  icml: [
    {
      label: "Extreme",
      value: "icml extreme",
    },
    {
      label: "Rhino Rx",
      value: "icml rhino rx",
    },
  ],
  bmw: [
    {
      label: "3 Series",
      value: "bmw 3 series",
    },
    {
      label: "5 Series",
      value: "bmw 5 series",
    },
    {
      label: "6 Series",
      value: "bmw 6 series",
    },
    {
      label: "X5",
      value: "bmw x5",
    },
    {
      label: "7 Series",
      value: "bmw 7 series",
    },
    {
      label: "X1",
      value: "bmw x1",
    },
    {
      label: "1 Series",
      value: "bmw 1 series",
    },
    {
      label: "X3",
      value: "bmw x3",
    },
    {
      label: "X6",
      value: "bmw x6",
    },
  ],
  volvo: [
    {
      label: "S60",
      value: "volvo s60",
    },
    {
      label: "Xc 90",
      value: "volvo xc 90",
    },
    {
      label: "S 80",
      value: "volvo s 80",
    },
    {
      label: "V40 Cross Country",
      value: "volvo v40 cross country",
    },
    {
      label: "Xc60",
      value: "volvo xc60",
    },
    {
      label: "Xc90",
      value: "volvo xc90",
    },
    {
      label: "V40",
      value: "volvo v40",
    },
  ],
  isuzu: [
    {
      label: "D-Max",
      value: "isuzu d-max",
    },
    {
      label: "Mu 7",
      value: "isuzu mu 7",
    },
    {
      label: "Mu-X",
      value: "isuzu mu-x",
    },
  ],
  ford: [
    {
      label: "Ecosport",
      value: "ford ecosport",
    },
    {
      label: "Figo",
      value: "ford figo",
    },
    {
      label: "Freestyle",
      value: "ford freestyle",
    },
    {
      label: "Aspire",
      value: "ford aspire",
    },
    {
      label: "Classic",
      value: "ford classic",
    },
    {
      label: "Ikon",
      value: "ford ikon",
    },
    {
      label: "Fiesta",
      value: "ford fiesta",
    },
    {
      label: "Endeavour",
      value: "ford endeavour",
    },
    {
      label: "Fusion",
      value: "ford fusion",
    },
  ],
  volkswagen: [
    {
      label: "Polo",
      value: "volkswagen polo",
    },
    {
      label: "Vento",
      value: "volkswagen vento",
    },
    {
      label: "Crosspolo",
      value: "volkswagen crosspolo",
    },
    {
      label: "Ameo",
      value: "volkswagen ameo",
    },
    {
      label: "Taigun",
      value: "volkswagen taigun",
    },
    {
      label: "Jetta",
      value: "volkswagen jetta",
    },
    {
      label: "Virtus",
      value: "volkswagen virtus",
    },
    {
      label: "Passat",
      value: "volkswagen passat",
    },
    {
      label: "Gti",
      value: "volkswagen gti",
    },
    {
      label: "Tiguan",
      value: "volkswagen tiguan",
    },
    {
      label: "Touareg",
      value: "volkswagen touareg",
    },
  ],
  skoda: [
    {
      label: "Yeti",
      value: "skoda yeti",
    },
    {
      label: "Rapid",
      value: "skoda rapid",
    },
    {
      label: "Fabia",
      value: "skoda fabia",
    },
    {
      label: "New Laura",
      value: "skoda new laura",
    },
    {
      label: "Superb",
      value: "skoda superb",
    },
    {
      label: "Kushaq",
      value: "skoda kushaq",
    },
    {
      label: "Octavia",
      value: "skoda octavia",
    },
    {
      label: "Slavia",
      value: "skoda slavia",
    },
  ],
  "mercedes-benz": [
    {
      label: "M-Class",
      value: "mercedes-benz m-class",
    },
    {
      label: "E-Class",
      value: "mercedes-benz e-class",
    },
    {
      label: "C-Class",
      value: "mercedes-benz c-class",
    },
    {
      label: "Cla",
      value: "mercedes-benz cla",
    },
    {
      label: "A Class",
      value: "mercedes-benz a class",
    },
    {
      label: "Gla Class",
      value: "mercedes-benz gla class",
    },
    {
      label: "S-Class",
      value: "mercedes-benz s-class",
    },
    {
      label: "B Class",
      value: "mercedes-benz b class",
    },
    {
      label: "Cls-Class",
      value: "mercedes-benz cls-class",
    },
    {
      label: "Gla",
      value: "mercedes-benz gla",
    },
    {
      label: "R-Class",
      value: "mercedes-benz r-class",
    },
    {
      label: "Gl-Class",
      value: "mercedes-benz gl-class",
    },
  ],
  audi: [
    {
      label: "A4",
      value: "audi a4",
    },
    {
      label: "Q3",
      value: "audi q3",
    },
    {
      label: "Q5",
      value: "audi q5",
    },
    {
      label: "A6",
      value: "audi a6",
    },
    {
      label: "Q7",
      value: "audi q7",
    },
    {
      label: "A3",
      value: "audi a3",
    },
    {
      label: "A7",
      value: "audi a7",
    },
  ],
  mg: [
    {
      label: "Hector",
      value: "mg hector",
    },
    {
      label: "Astor",
      value: "mg astor",
    },
    {
      label: "Hector Plus",
      value: "mg hector plus",
    },
  ],
  jeep: [
    {
      label: "Compass",
      value: "jeep compass",
    },
    {
      label: "Compass Trailhawk",
      value: "jeep compass trailhawk",
    },
  ],
  fiat: [
    {
      label: "Grande Punto",
      value: "fiat grande punto",
    },
    {
      label: "Punto",
      value: "fiat punto",
    },
    {
      label: "Linea",
      value: "fiat linea",
    },
    {
      label: "Punto Pure",
      value: "fiat punto pure",
    },
    {
      label: "Punto Evo",
      value: "fiat punto evo",
    },
    {
      label: "Palio",
      value: "fiat palio",
    },
    {
      label: "Avventura",
      value: "fiat avventura",
    },
    {
      label: "Linea Classic",
      value: "fiat linea classic",
    },
    {
      label: "Avventura Urban Cross",
      value: "fiat avventura urban cross",
    },
    {
      label: "Adventure",
      value: "fiat adventure",
    },
    {
      label: "Punto Abarth",
      value: "fiat punto abarth",
    },
  ],
  "land rover": [
    {
      label: "Freelander 2",
      value: "land rover freelander 2",
    },
    {
      label: "Range Rover Evoque",
      value: "land rover range rover evoque",
    },
  ],
  jaguar: [
    {
      label: "Xf",
      value: "jaguar xf",
    },
    {
      label: "Xj",
      value: "jaguar xj",
    },
  ],
  mitsubishi: [
    {
      label: "Outlander",
      value: "mitsubishi outlander",
    },
    {
      label: "Pajero",
      value: "mitsubishi pajero",
    },
    {
      label: "Lancer",
      value: "mitsubishi lancer",
    },
    {
      label: "Montero",
      value: "mitsubishi montero",
    },
    {
      label: "Cedia",
      value: "mitsubishi cedia",
    },
  ],
  mini: [
    {
      label: "Cooper",
      value: "mini cooper",
    },
    {
      label: "Cooper Countryman",
      value: "mini cooper countryman",
    },
  ],
  porsche: [
    {
      label: "Cayenne",
      value: "porsche cayenne",
    },
  ],
  citroen: [
    {
      label: "C3",
      value: "citroen c3",
    },
  ],
  ambassador: [
    {
      label: "",
      value: "ambassador",
    },
  ],
  premier: [
    {
      label: "Rio",
      value: "premier rio",
    },
  ],
  opel: [
    {
      label: "Corsa",
      value: "opelcorsa",
    },
  ],
};

export const gearsBox = [
  { label: "1 speed", value: "1 speed" },
  { label: "4 speed", value: "4 speed" },
  { label: "5 speed", value: "5 speed" },
  { label: "6 speed", value: "6 speed" },
  { label: "7 speed", value: "7 speed" },
  { label: "8 speed", value: "8 speed" },
  { label: "9 speed", value: "9 speed" },
  { label: "cvt", value: "cvt" },
  { label: "direct drive", value: "direct drive" },
  { label: "fully automatic", value: "fully automatic" },
];

export const steeringType = [
  { label: "power", value: "power", id: "power" },
  { label: "manual", value: "manual", id: "manual" },
];

export const noOfCylinders = [
  { label: "1", value: "1" },
  { label: "2", value: "2" },
  { label: "3", value: "3" },
  { label: "4", value: "4" },
  { label: "5", value: "5" },
  { label: "6", value: "6" },
  { label: "7", value: "7" },
  { label: "8", value: "8" },
  { label: "16", value: "16" },
];

// export const seats = [
//   { label: "0", value: "0" },
//   { label: "2", value: "2" },
//   { label: "4", value: "4" },
//   { label: "5", value: "5" },
//   { label: "6", value: "6" },
//   { label: "7", value: "7" },
//   { label: "8", value: "8" },
//   { label: "9", value: "9" },
//   { label: "10", value: "10" },
//   { label: "13", value: "13" },
//   { label: "14", value: "14" },
// ];

export const superCharger = [
  { label: "Yes", value: "1", id: "1" },
  { label: "No", value: "0", id: "0" },
];

export const features = [
  { label: "power steering", value: "power steering" },
  { label: "power windows front", value: "power windows front" },
  { label: "air conditioner", value: "air conditioner" },
  { label: "heater", value: "heater" },
  { label: "adjustable head lights", value: "adjustable head lights" },
  {
    label: "manually adjustable exterior rear view mirror",
    value: "manually adjustable exterior rear view mirror",
  },
  { label: "centeral locking", value: "centeral locking" },
  { label: "child safety locks", value: "child safety locks" },
  { label: "number of speaker", value: "number of speaker" },
  { label: "digital odometer", value: "digital odometer" },
  { label: "electronic multi tripmeter", value: "electronic multi tripmeter" },
  { label: "fabric upholstery", value: "fabric upholstery" },
  { label: "glove compartment", value: "glove compartment" },
  { label: "dual tone dashboard", value: "dual tone dashboard" },
  { label: "adjustable steering", value: "adjustable steering" },
  { label: "digital clock", value: "digital clock" },
  { label: "power windows rear", value: "power windows rear" },
  { label: "remote trunk opener", value: "remote trunk opener" },
  { label: "remote fuel lid opener", value: "remote fuel lid opener" },
  { label: "low fuel warning light", value: "low fuel warning light" },
  { label: "accessory power outlet", value: "accessory power outlet" },
  { label: "vanity mirror", value: "vanity mirror" },
  { label: "rear seat headrest", value: "rear seat headrest" },
  { label: "cup holders front", value: "cup holders front" },
];

export const featureWeight = {
  "power steering": 1,
  "power windows front": 1,
  "air conditioner": 1,
  heater: 1,
  "adjustable head lights": 2,
  "manually adjustable exterior rear view mirror": 1,
  "centeral locking": 2,
  "child safety locks": 2,
  "number of speaker": 1,
  "digital odometer": 1,
  "electronic multi tripmeter": 1,
  "fabric upholstery": 1,
  "glove compartment": 1,
  "dual tone dashboard": 1,
  "adjustable steering": 1,
  "digital clock": 1,
  "power windows rear": 1,
  "remote trunk opener": 1,
  "remote fuel lid opener": 1,
  "low fuel warning light": 1,
  "accessory power outlet": 1,
  "vanity mirror": 1,
  "rear seat headrest": 1,
  "cup holders front": 1,
};

export const seatsByGroup = {
  5: [
    "maruti wagon r",
    "maruti celerio",
    "maruti alto",
    "maruti swift dzire tour",
    "maruti eeco",
    "maruti estilo",
    "maruti alto k10",
    "maruti alto 800",
    "maruti zen estilo",
    "maruti celerio tour 2018-2021",
    "maruti sx4",
    "maruti swift dzire",
    "maruti omni",
    "maruti s-presso",
    "maruti swift",
    "maruti 800",
    "maruti ciaz",
    "maruti baleno",
    "maruti ignis",
    "maruti vitara brezza",
    "maruti sx4 s cross",
    "maruti ritz",
    "maruti ciaz s",
    "maruti a-star",
    "maruti celerio x",
    "maruti wagon r stingray",
    "maruti esteem",
    "maruti grand vitara",
    "maruti baleno rs",
    "maruti brezza",
    "maruti zen",
    "maruti alto 2021",
    "maruti kizashi",
    "honda amaze",
    "honda city",
    "honda jazz",
    "honda wr-v",
    "honda brio",
    "honda cr-v",
    "honda civic",
    "honda accord",
    "hyundai grand i10",
    "hyundai santro",
    "hyundai aura",
    "hyundai grand i10 nios",
    "hyundai accent",
    "hyundai santro xing",
    "hyundai xcent prime",
    "hyundai xcent",
    "hyundai i10",
    "hyundai eon",
    "hyundai kona",
    "hyundai verna",
    "hyundai creta",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 active",
    "hyundai elantra",
    "hyundai elite i20 2018",
    "hyundai getz",
    "hyundai sonata",
    "hyundai i20 n line",
    "hyundai tucson",
    "tata tiago",
    "tata tigor",
    "tata tiago nrg",
    "tata indigo",
    "tata indica",
    "tata tigor ev",
    "tata nexon ev prime",
    "tata nexon ev max",
    "tata indigo marina",
    "tata xenon xt",
    "tata nexon",
    "tata altroz",
    "tata harrier",
    "tata indica ev2",
    "tata punch",
    "tata zest",
    "tata manza",
    "tata bolt",
    "tata indica xeta",
    "toyota corolla altis",
    "toyota camry",
    "toyota prius",
    "toyota glanza",
    "toyota urban cruiser",
    "toyota etios liva",
    "toyota etios",
    "toyota etios cross",
    "toyota yaris",
    "toyota etios 2014-2016",
    "toyota corolla",
    "toyota platinum etios",
    "mahindra kuv 100 nxt",
    "mahindra e2o",
    "mahindra e verito",
    "mahindra scorpio",
    "mahindra bolero pik up extra strong",
    "mahindra bolero camper",
    "mahindra renault logan",
    "mahindra xuv300",
    "mahindra kuv 100",
    "mahindra verito",
    "mahindra verito vibe",
    "mahindra xuv700",
    "mahindra logan",
    "chevrolet aveo",
    "chevrolet spark",
    "chevrolet beat",
    "chevrolet cruze",
    "chevrolet sail hatchback",
    "chevrolet sail",
    "chevrolet aveo u-va",
    "chevrolet optra",
    "renault duster",
    "renault pulse",
    "renault kiger",
    "renault kwid",
    "renault captur",
    "renault scala",
    "renault fluence",
    "renault koleos",
    "nissan micra",
    "nissan magnite",
    "nissan terrano",
    "nissan sunny",
    "nissan micra active",
    "nissan teana",
    "nissan kicks",
    "nissan x-trail",
    "datsun go",
    "datsun redigo",
    "kia seltos",
    "kia sonet",
    "bmw 3 series",
    "bmw 5 series",
    "bmw x5",
    "bmw 7 series",
    "bmw x1",
    "bmw 1 series",
    "bmw x3",
    "bmw x6",
    "volvo s60",
    "volvo s 80",
    "volvo v40 cross country",
    "volvo xc60",
    "volvo v40",
    "isuzu d-max",
    "ford ecosport",
    "ford figo",
    "ford freestyle",
    "ford aspire",
    "ford classic",
    "ford ikon",
    "ford fiesta",
    "ford endeavour",
    "ford fusion",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen crosspolo",
    "volkswagen ameo",
    "volkswagen taigun",
    "volkswagen jetta",
    "volkswagen virtus",
    "volkswagen passat",
    "volkswagen gti",
    "volkswagen tiguan",
    "volkswagen touareg",
    "skoda yeti",
    "skoda rapid",
    "skoda fabia",
    "skoda new laura",
    "skoda superb",
    "skoda kushaq",
    "skoda octavia",
    "skoda slavia",
    "mercedes-benz m-class",
    "mercedes-benz e-class",
    "mercedes-benz c-class",
    "mercedes-benz cla",
    "mercedes-benz a class",
    "mercedes-benz gla class",
    "mercedes-benz s-class",
    "mercedes-benz b class",
    "mercedes-benz gla",
    "audi a4",
    "audi q3",
    "audi q5",
    "audi a6",
    "audi a3",
    "audi a7",
    "mg hector",
    "mg astor",
    "jeep compass",
    "jeep compass trailhawk",
    "fiat grande punto",
    "fiat punto",
    "fiat linea",
    "fiat punto pure",
    "fiat punto evo",
    "fiat palio",
    "fiat avventura",
    "fiat linea classic",
    "fiat avventura urban cross",
    "fiat adventure",
    "fiat punto abarth",
    "land rover freelander 2",
    "land rover range rover evoque",
    "jaguar xf",
    "jaguar xj",
    "mitsubishi outlander",
    "mitsubishi lancer",
    "mitsubishi cedia",
    "mini cooper",
    "mini cooper countryman",
    "porsche cayenne",
    "citroen c3",
    "ambassador",
    "premier rio",
    "opelcorsa",
  ],
  7: [
    "maruti ertiga",
    "maruti ertiga tour",
    "maruti eeco",
    "honda mobilio",
    "honda br-v",
    "hyundai santa fe",
    "hyundai tucson",
    "hyundai alcazar",
    "tata sumo victa",
    "tata hexa",
    "tata aria",
    "tata sumo",
    "tata venture",
    "tata safari storme",
    "tata new safari",
    "toyota innova",
    "toyota innova crysta",
    "toyota fortuner",
    "mahindra marazzo",
    "mahindra xylo",
    "mahindra scorpio",
    "mahindra bolero",
    "mahindra ssangyong rexton",
    "mahindra bolero power plus",
    "mahindra thar",
    "mahindra xuv500",
    "mahindra tuv 300",
    "mahindra quanto",
    "mahindra bolero neo",
    "mahindra nuvosport",
    "mahindra xuv700",
    "chevrolet tavera",
    "chevrolet enjoy",
    "chevrolet captiva",
    "chevrolet trailblazer",
    "renault triber",
    "renault lodgy",
    "nissan evalia",
    "datsun go plus",
    "kia carens",
    "force one",
    "force gurkha",
    "icml extreme",
    "volvo xc 90",
    "volvo xc90",
    "isuzu mu 7",
    "isuzu mu-x",
    "ford endeavour",
    "mercedes-benz r-class",
    "mercedes-benz gl-class",
    "audi q7",
    "mg hector plus",
    "mitsubishi pajero",
    "mitsubishi montero",
  ],
  2: [
    "maruti eeco cargo",
    "maruti super carry",
    "tata yodha pickup",
    "mahindra bolero maxi truck plus",
    "mahindra bolero pik up extra strong",
    "mahindra bolero pik up extra long",
  ],
  4: [
    "maruti alto k10",
    "maruti alto 800",
    "maruti s-presso",
    "maruti 800",
    "tata nano",
    "tata yodha pickup",
    "bajaj re60",
    "mahindra e2o plus",
    "mahindra thar",
    "mahindra xuv300",
    "force gurkha",
    "bmw 6 series",
    "mercedes-benz cls-class",
    "mini cooper",
  ],
  6: [
    "maruti xl6",
    "hyundai alcazar",
    "mahindra kuv 100 nxt",
    "mahindra thar",
    "mahindra kuv 100",
    "kia carens",
    "force one",
    "force gurkha",
    "mg hector plus",
    "mitsubishi pajero",
  ],
  8: [
    "maruti omni",
    "maruti gypsy",
    "tata sumo",
    "toyota innova",
    "toyota innova crysta",
    "toyota prado",
    "mahindra marazzo",
    "mahindra xylo",
    "mahindra scorpio",
    "mahindra bolero",
    "mahindra supro",
    "chevrolet tavera",
    "chevrolet enjoy",
    "renault lodgy",
    "ashok leyland stile",
  ],
  0: ["maruti omni", "tata indica"],
  9: [
    "tata sumo victa",
    "tata sumo",
    "mahindra scorpio",
    "mahindra bolero",
    "mahindra bolero power plus",
    "mahindra tuv 300 plus",
    "chevrolet tavera",
  ],
  10: ["tata sumo victa", "chevrolet tavera", "icml rhino rx"],
  14: ["tata winger"],
  13: ["force trax cruiser"],
};

export const gearBoxGroup = {
  "1 speed": ["hyundai kona", "tata tigor ev"],
  "4 speed": [
    "maruti ertiga",
    "maruti xl6",
    "maruti sx4",
    "maruti swift dzire",
    "maruti omni",
    "maruti 800",
    "maruti ciaz",
    "maruti vitara brezza",
    "maruti sx4 s cross",
    "maruti ritz",
    "maruti a-star",
    "maruti grand vitara",
    "hyundai grand i10",
    "hyundai xcent",
    "hyundai i10",
    "hyundai verna",
    "hyundai i20",
    "tata nano",
    "toyota urban cruiser",
    "toyota fortuner",
    "toyota corolla",
    "mahindra renault logan",
  ],
  "5 speed": [
    "maruti wagon r",
    "maruti celerio",
    "maruti ertiga",
    "maruti alto",
    "maruti ertiga tour",
    "maruti swift dzire tour",
    "maruti eeco",
    "maruti estilo",
    "maruti eeco cargo",
    "maruti alto k10",
    "maruti alto 800",
    "maruti zen estilo",
    "maruti celerio tour 2018-2021",
    "maruti xl6",
    "maruti sx4",
    "maruti swift dzire",
    "maruti omni",
    "maruti s-presso",
    "maruti swift",
    "maruti super carry",
    "maruti ciaz",
    "maruti baleno",
    "maruti ignis",
    "maruti vitara brezza",
    "maruti sx4 s cross",
    "maruti ritz",
    "maruti ciaz s",
    "maruti a-star",
    "maruti celerio x",
    "maruti wagon r stingray",
    "maruti esteem",
    "maruti grand vitara",
    "maruti baleno rs",
    "maruti brezza",
    "maruti zen",
    "maruti alto 2021",
    "maruti gypsy",
    "honda amaze",
    "honda city",
    "honda mobilio",
    "honda jazz",
    "honda wr-v",
    "honda brio",
    "honda cr-v",
    "honda civic",
    "honda accord",
    "hyundai grand i10",
    "hyundai santro",
    "hyundai aura",
    "hyundai grand i10 nios",
    "hyundai accent",
    "hyundai santro xing",
    "hyundai xcent prime",
    "hyundai xcent",
    "hyundai i10",
    "hyundai eon",
    "hyundai verna",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 active",
    "hyundai getz",
    "hyundai sonata",
    "hyundai i20 n line",
    "hyundai tucson",
    "tata tiago",
    "tata nano",
    "tata tigor",
    "tata tiago nrg",
    "tata indigo",
    "tata indica",
    "tata nexon ev prime",
    "tata nexon ev max",
    "tata sumo victa",
    "tata hexa",
    "tata aria",
    "tata indigo marina",
    "tata sumo",
    "tata winger",
    "tata venture",
    "tata xenon xt",
    "tata yodha pickup",
    "tata altroz",
    "tata indica ev2",
    "tata punch",
    "tata zest",
    "tata manza",
    "tata safari storme",
    "tata bolt",
    "tata new safari",
    "tata indica xeta",
    "toyota camry",
    "toyota innova",
    "toyota innova crysta",
    "toyota prius",
    "toyota glanza",
    "toyota urban cruiser",
    "toyota etios liva",
    "toyota etios",
    "toyota etios cross",
    "toyota fortuner",
    "toyota etios 2014-2016",
    "toyota corolla",
    "toyota platinum etios",
    "toyota prado",
    "bajaj re60",
    "mahindra bolero maxi truck plus",
    "mahindra kuv 100 nxt",
    "mahindra xylo",
    "mahindra scorpio",
    "mahindra bolero",
    "mahindra supro",
    "mahindra bolero pik up extra strong",
    "mahindra bolero pik up extra long",
    "mahindra bolero camper",
    "mahindra ssangyong rexton",
    "mahindra renault logan",
    "mahindra bolero power plus",
    "mahindra thar",
    "mahindra tuv 300",
    "mahindra kuv 100",
    "mahindra verito",
    "mahindra quanto",
    "mahindra bolero neo",
    "mahindra nuvosport",
    "mahindra verito vibe",
    "mahindra logan",
    "chevrolet aveo",
    "chevrolet spark",
    "chevrolet beat",
    "chevrolet tavera",
    "chevrolet enjoy",
    "chevrolet cruze",
    "chevrolet sail hatchback",
    "chevrolet sail",
    "chevrolet aveo u-va",
    "chevrolet captiva",
    "chevrolet optra",
    "renault triber",
    "renault lodgy",
    "renault duster",
    "renault pulse",
    "renault kiger",
    "renault kwid",
    "renault captur",
    "renault scala",
    "nissan evalia",
    "nissan micra",
    "nissan magnite",
    "nissan terrano",
    "nissan sunny",
    "nissan micra active",
    "nissan teana",
    "nissan kicks",
    "datsun go plus",
    "datsun go",
    "datsun redigo",
    "kia seltos",
    "kia sonet",
    "force trax cruiser",
    "force one",
    "force gurkha",
    "icml extreme",
    "icml rhino rx",
    "ashok leyland stile",
    "bmw x3",
    "isuzu d-max",
    "isuzu mu 7",
    "isuzu mu-x",
    "ford ecosport",
    "ford figo",
    "ford freestyle",
    "ford aspire",
    "ford classic",
    "ford ikon",
    "ford fiesta",
    "ford endeavour",
    "ford fusion",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen crosspolo",
    "volkswagen ameo",
    "volkswagen jetta",
    "volkswagen touareg",
    "skoda yeti",
    "skoda rapid",
    "skoda fabia",
    "skoda new laura",
    "skoda superb",
    "skoda octavia",
    "mercedes-benz e-class",
    "mercedes-benz c-class",
    "mg astor",
    "fiat grande punto",
    "fiat punto",
    "fiat linea",
    "fiat punto pure",
    "fiat punto evo",
    "fiat palio",
    "fiat avventura",
    "fiat linea classic",
    "fiat avventura urban cross",
    "fiat adventure",
    "fiat punto abarth",
    "mitsubishi pajero",
    "mitsubishi lancer",
    "mitsubishi montero",
    "mitsubishi cedia",
    "ambassador",
    "premier rio",
    "opelcorsa",
  ],

  "6 speed": [
    "maruti ertiga",
    "maruti xl6",
    "maruti sx4 s cross",
    "maruti kizashi",
    "honda city",
    "honda jazz",
    "honda wr-v",
    "honda cr-v",
    "honda br-v",
    "honda civic",
    "hyundai verna",
    "hyundai creta",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 active",
    "hyundai elantra",
    "hyundai elite i20 2018",
    "hyundai sonata",
    "hyundai santa fe",
    "hyundai tucson",
    "hyundai alcazar",
    "tata indica",
    "tata hexa",
    "tata nexon",
    "tata altroz",
    "tata harrier",
    "tata safari storme",
    "tata new safari",
    "toyota corolla altis",
    "toyota camry",
    "toyota innova crysta",
    "toyota fortuner",
    "toyota yaris",
    "mahindra marazzo",
    "mahindra scorpio",
    "mahindra thar",
    "mahindra xuv500",
    "mahindra xuv300",
    "mahindra xuv700",
    "mahindra tuv 300 plus",
    "chevrolet cruze",
    "chevrolet captiva",
    "chevrolet trailblazer",
    "renault lodgy",
    "renault duster",
    "renault captur",
    "renault fluence",
    "renault koleos",
    "nissan terrano",
    "nissan kicks",
    "nissan x-trail",
    "kia carens",
    "kia seltos",
    "kia sonet",
    "bmw 3 series",
    "bmw 5 series",
    "bmw x5",
    "bmw 7 series",
    "bmw x3",
    "bmw x6",
    "volvo s60",
    "volvo s 80",
    "volvo v40 cross country",
    "volvo xc60",
    "volvo xc90",
    "volvo v40",
    "isuzu d-max",
    "ford ecosport",
    "ford figo",
    "ford aspire",
    "ford endeavour",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen taigun",
    "volkswagen jetta",
    "volkswagen virtus",
    "volkswagen passat",
    "skoda yeti",
    "skoda rapid",
    "skoda new laura",
    "skoda superb",
    "skoda kushaq",
    "skoda octavia",
    "skoda slavia",
    "mercedes-benz c-class",
    "audi a4",
    "audi q3",
    "audi a6",
    "audi a3",
    "mg hector",
    "mg hector plus",
    "jeep compass",
    "land rover freelander 2",
    "mitsubishi outlander",
    "mini cooper",
    "mini cooper countryman",
    "citroen c3",
  ],

  "7 speed": [
    "honda jazz",
    "hyundai verna",
    "hyundai creta",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 n line",
    "toyota corolla altis",
    "toyota yaris",
    "renault duster",
    "kia carens",
    "kia seltos",
    "kia sonet",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen ameo",
    "volkswagen virtus",
    "volkswagen gti",
    "volkswagen tiguan",
    "skoda rapid",
    "skoda superb",
    "skoda kushaq",
    "skoda octavia",
    "mercedes-benz m-class",
    "mercedes-benz e-class",
    "mercedes-benz c-class",
    "mercedes-benz cla",
    "mercedes-benz a class",
    "mercedes-benz gla class",
    "mercedes-benz s-class",
    "mercedes-benz b class",
    "mercedes-benz cls-class",
    "mercedes-benz gla",
    "mercedes-benz r-class",
    "mercedes-benz gl-class",
    "audi a4",
    "audi q3",
    "audi q5",
    "audi a6",
    "audi a3",
    "audi a7",
    "jeep compass",
  ],

  "8 speed": [
    "nissan teana",
    "bmw 3 series",
    "bmw 5 series",
    "bmw 6 series",
    "bmw x5",
    "bmw 7 series",
    "bmw x1",
    "bmw 1 series",
    "bmw x3",
    "volvo s60",
    "volvo xc 90",
    "volvo xc60",
    "audi a4",
    "audi a6",
    "audi q7",
    "mg hector",
    "mg astor",
    "jaguar xf",
    "jaguar xj",
    "porsche cayenne",
  ],
  "9 speed": [
    "mercedes-benz c-class",
    "jeep compass",
    "jeep compass trailhawk",
    "land rover range rover evoque",
  ],
  "fully automatic": ["mahindra e2o", "mahindra e verito", "bmw x1"],
  "direct drive": ["mahindra e2o plus"],
  cvt: [
    "maruti baleno",
    "honda amaze",
    "honda city",
    "honda br-v",
    "honda civic",
    "toyota camry",
    "renault kiger",
    "nissan micra",
    "nissan magnite",
    "nissan sunny",
  ],
};

export const cylinderGroup = {
  1: ["bajaj re60", "chevrolet optra", "fiat adventure"],
  2: [
    "maruti celerio",
    "hyundai xcent",
    "tata nano",
    "mahindra e2o",
    "mahindra supro",
  ],
  3: [
    "maruti wagon r",
    "maruti celerio",
    "maruti alto",
    "maruti estilo",
    "maruti alto k10",
    "maruti alto 800",
    "maruti zen estilo",
    "maruti celerio tour 2018-2021",
    "maruti omni",
    "maruti s-presso",
    "maruti 800",
    "maruti baleno",
    "maruti a-star",
    "maruti celerio x",
    "maruti wagon r stingray",
    "maruti baleno rs",
    "maruti alto 2021",
    "hyundai grand i10",
    "hyundai aura",
    "hyundai grand i10 nios",
    "hyundai santro xing",
    "hyundai xcent",
    "hyundai eon",
    "hyundai verna",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 n line",
    "tata tiago",
    "tata tigor",
    "tata tiago nrg",
    "tata nexon",
    "tata altroz",
    "tata punch",
    "mahindra kuv 100 nxt",
    "mahindra bolero",
    "mahindra xuv300",
    "mahindra tuv 300",
    "mahindra kuv 100",
    "mahindra quanto",
    "mahindra bolero neo",
    "mahindra nuvosport",
    "chevrolet beat",
    "renault triber",
    "renault pulse",
    "renault kiger",
    "renault kwid",
    "nissan micra",
    "nissan magnite",
    "nissan micra active",
    "datsun go plus",
    "datsun go",
    "datsun redigo",
    "kia sonet",
    "ford ecosport",
    "ford figo",
    "ford freestyle",
    "ford aspire",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen ameo",
    "volkswagen taigun",
    "volkswagen virtus",
    "skoda rapid",
    "skoda fabia",
    "skoda kushaq",
    "skoda slavia",
    "citroen c3",
  ],
  4: [
    "maruti wagon r",
    "maruti ertiga",
    "maruti ertiga tour",
    "maruti swift dzire tour",
    "maruti eeco",
    "maruti estilo",
    "maruti eeco cargo",
    "maruti zen estilo",
    "maruti xl6",
    "maruti sx4",
    "maruti swift dzire",
    "maruti omni",
    "maruti swift",
    "maruti super carry",
    "maruti ciaz",
    "maruti baleno",
    "maruti ignis",
    "maruti vitara brezza",
    "maruti sx4 s cross",
    "maruti ritz",
    "maruti ciaz s",
    "maruti esteem",
    "maruti grand vitara",
    "maruti brezza",
    "maruti zen",
    "maruti gypsy",
    "maruti kizashi",
    "honda amaze",
    "honda city",
    "honda mobilio",
    "honda jazz",
    "honda wr-v",
    "honda brio",
    "honda cr-v",
    "honda br-v",
    "honda civic",
    "honda accord",
    "hyundai grand i10",
    "hyundai santro",
    "hyundai aura",
    "hyundai grand i10 nios",
    "hyundai accent",
    "hyundai santro xing",
    "hyundai xcent prime",
    "hyundai xcent",
    "hyundai i10",
    "hyundai kona",
    "hyundai verna",
    "hyundai creta",
    "hyundai i20",
    "hyundai venue",
    "hyundai i20 active",
    "hyundai elantra",
    "hyundai elite i20 2018",
    "hyundai getz",
    "hyundai sonata",
    "hyundai santa fe",
    "hyundai tucson",
    "hyundai alcazar",
    "tata indigo",
    "tata indica",
    "tata tigor ev",
    "tata nexon ev prime",
    "tata nexon ev max",
    "tata sumo victa",
    "tata hexa",
    "tata aria",
    "tata indigo marina",
    "tata sumo",
    "tata winger",
    "tata venture",
    "tata xenon xt",
    "tata yodha pickup",
    "tata nexon",
    "tata altroz",
    "tata harrier",
    "tata indica ev2",
    "tata zest",
    "tata manza",
    "tata safari storme",
    "tata bolt",
    "tata new safari",
    "tata indica xeta",
    "toyota corolla altis",
    "toyota camry",
    "toyota innova",
    "toyota innova crysta",
    "toyota prius",
    "toyota glanza",
    "toyota urban cruiser",
    "toyota etios liva",
    "toyota etios",
    "toyota etios cross",
    "toyota fortuner",
    "toyota yaris",
    "toyota etios 2014-2016",
    "toyota corolla",
    "toyota platinum etios",
    "mahindra bolero maxi truck plus",
    "mahindra e2o plus",
    "mahindra e verito",
    "mahindra marazzo",
    "mahindra xylo",
    "mahindra scorpio",
    "mahindra bolero",
    "mahindra bolero pik up extra strong",
    "mahindra bolero pik up extra long",
    "mahindra bolero camper",
    "mahindra renault logan",
    "mahindra bolero power plus",
    "mahindra thar",
    "mahindra xuv500",
    "mahindra xuv300",
    "mahindra verito",
    "mahindra verito vibe",
    "mahindra xuv700",
    "mahindra logan",
    "mahindra tuv 300 plus",
    "chevrolet aveo",
    "chevrolet spark",
    "chevrolet beat",
    "chevrolet tavera",
    "chevrolet enjoy",
    "chevrolet cruze",
    "chevrolet sail hatchback",
    "chevrolet sail",
    "chevrolet aveo u-va",
    "chevrolet captiva",
    "chevrolet optra",
    "chevrolet trailblazer",
    "renault lodgy",
    "renault duster",
    "renault pulse",
    "renault captur",
    "renault scala",
    "renault fluence",
    "renault koleos",
    "nissan evalia",
    "nissan micra",
    "nissan terrano",
    "nissan sunny",
    "nissan teana",
    "nissan kicks",
    "nissan x-trail",
    "kia carens",
    "kia seltos",
    "kia sonet",
    "force trax cruiser",
    "force one",
    "force gurkha",
    "icml extreme",
    "icml rhino rx",
    "ashok leyland stile",
    "bmw 3 series",
    "bmw 5 series",
    "bmw x1",
    "bmw 1 series",
    "bmw x3",
    "volvo s60",
    "volvo xc 90",
    "volvo v40 cross country",
    "isuzu d-max",
    "isuzu mu 7",
    "isuzu mu-x",
    "ford ecosport",
    "ford figo",
    "ford freestyle",
    "ford aspire",
    "ford classic",
    "ford ikon",
    "ford fiesta",
    "ford endeavour",
    "ford fusion",
    "volkswagen polo",
    "volkswagen vento",
    "volkswagen crosspolo",
    "volkswagen ameo",
    "volkswagen jetta",
    "volkswagen virtus",
    "volkswagen passat",
    "volkswagen gti",
    "volkswagen tiguan",
    "volkswagen touareg",
    "skoda yeti",
    "skoda rapid",
    "skoda fabia",
    "skoda new laura",
    "skoda superb",
    "skoda kushaq",
    "skoda octavia",
    "mercedes-benz m-class",
    "mercedes-benz e-class",
    "mercedes-benz c-class",
    "mercedes-benz cla",
    "mercedes-benz a class",
    "mercedes-benz gla class",
    "mercedes-benz b class",
    "mercedes-benz gla",
    "audi a4",
    "audi q3",
    "audi q5",
    "audi a6",
    "audi a3",
    "mg hector",
    "mg astor",
    "mg hector plus",
    "jeep compass",
    "jeep compass trailhawk",
    "fiat grande punto",
    "fiat punto",
    "fiat linea",
    "fiat punto pure",
    "fiat punto evo",
    "fiat palio",
    "fiat avventura",
    "fiat linea classic",
    "fiat avventura urban cross",
    "fiat punto abarth",
    "land rover freelander 2",
    "land rover range rover evoque",
    "jaguar xf",
    "mitsubishi outlander",
    "mitsubishi pajero",
    "mitsubishi lancer",
    "mitsubishi montero",
    "mitsubishi cedia",
    "mini cooper",
    "mini cooper countryman",
    "ambassador",
    "premier rio",
    "opelcorsa",
  ],
  5: [
    "mahindra ssangyong rexton",
    "volvo s60",
    "volvo s 80",
    "volvo v40 cross country",
    "volvo xc60",
    "volvo xc90",
    "volvo v40",
  ],
  6: [
    "honda accord",
    "toyota prado",
    "nissan teana",
    "bmw 3 series",
    "bmw 5 series",
    "bmw x5",
    "bmw 7 series",
    "bmw x3",
    "bmw x6",
    "volvo s60",
    "skoda superb",
    "mercedes-benz m-class",
    "mercedes-benz e-class",
    "mercedes-benz s-class",
    "mercedes-benz cls-class",
    "mercedes-benz r-class",
    "mercedes-benz gl-class",
    "audi q5",
    "audi a6",
    "audi q7",
    "audi a7",
    "jaguar xf",
    "jaguar xj",
  ],
  7: ["toyota innova crysta"],
  8: [
    "bmw 6 series",
    "bmw x5",
    "mercedes-benz s-class",
    "audi q7",
    "porsche cayenne",
  ],
  16: ["mahindra e2o plus"],
};
